# Generated by Django 4.2.24 on 2025-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sabji_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabji',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
